window.EDUKIDS_CONFIG = Object.freeze({
  BRAND_NAME: "Educação Kids",
  BASIC_PRICE: 10.00,
  COMPLETE_PRICE: 27.90,
  UPSELL_PRICE: 22.00,
  EXIT_PRICE: 17.90,
  MAIN_ACTIVITY_COUNT: "130+",
  BIBLE_ACTIVITY_COUNT: "400+",
  CHECKOUT_BASIC_URL: "https://SEU-CHECKOUT-BASICO.com",
  CHECKOUT_COMPLETE_URL: "https://SEU-CHECKOUT-COMPLETO.com",
  CHECKOUT_UPSELL_URL: "https://SEU-CHECKOUT-UPSELL.com",
  CHECKOUT_EXIT_URL: "https://SEU-CHECKOUT-EXIT.com",
  SUPPORT_EMAIL: "SEU-EMAIL@DOMINIO.com",
  WHATSAPP: "5500000000000",
  ENABLE_DESKTOP_EXIT_INTENT: true,
  ENABLE_BACK_EXIT_OFFER: true
});
